# Generated by Django 5.2.3 on 2025-06-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=140)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('content', models.CharField()),
            ],
        ),
    ]
